apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: cv-retail
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-medium
  imageName: ent.box.com/shared/static/9eyur2evurwa8k1x7bjot6m6klbhi1rd.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Internal Network"
    ethernetCardType: "vmxnet3"
