apiVersion: v1
kind: Namespace
metadata:
  name: squid-namespace  # Define a namespace for your resources

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: squid-namespace
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: scbunn/squid:latest  # You can also use another image like sameersbn/squid
          ports:
            - containerPort: 3128
          volumeMounts:
            - name: squid-cache
              mountPath: /var/cache/squid
            - name: squid-config
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
          resources:
            requests:
              memory: "256Mi"  # Minimum memory required
            limits:
              memory: "384Mi"  # Maximum memory allowed
      volumes:
        - name: squid-cache
          emptyDir: {}  # Use a persistent volume for production
        - name: squid-config
          configMap:
            name: squid-config

---

apiVersion: v1
kind: Service
metadata:
  name: squid-service
  namespace: squid-namespace
spec:
  type: NodePort
  ports:
    - port: 3128
      targetPort: 3128
      nodePort: 30000  # You can specify a port or let Kubernetes assign one
  selector:
    app: squid

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: squid-config
  namespace: squid-namespace 
data:
  squid.conf: |
    http_port 3128
    acl localnet src 192.168.50.0/24  # Adjust this ACL as needed
    http_access allow localnet
    http_access deny all

