apiVersion: v1
kind: Namespace
metadata:
  name: windows
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: win-10-term
  namespace: windows
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-small
  imageName: 192.168.50.121/downloads/win10.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Internal Network"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    configMapName: user-data-windows-1
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-windows-1
    namespace: windows
data:
  user-data: |
    #ps1
    Install-WindowsFeature -Name Print-Server
    Restart-Computer
